Fix AttributeError for 'arith_ast.get_type' to 'arith_ast.elem_type'
Fix: AttributeError: 'Element' object has no attribute 'get_type'.

Changed to 'elem_type'